import { Dusa } from 'dusa';
import * as fs from 'node:fs';

const RULES_FILE_1 = 'counterpoint_opt.du';
const RULES_FILE_2 = 'counterpoint_forbid.du';
const SONG_FILE = 'song-16.du';
const TRIALS = 10;

const songText = fs.readFileSync(SONG_FILE, 'utf8');
console.log(`Song: ${SONG_FILE}`);

function checkRules(fromFile, toFile) {
  const fromProgram = fs.readFileSync(fromFile, 'utf8') + '\n' + songText;
  const toRules = fs.readFileSync(toFile, 'utf8');
  const solver = new Dusa(fromProgram).solve();

  console.log('');
  console.log(`Checking whether ${toFile} accepts solutions generated by ${fromFile}:`);

  for (let trial = 1; trial <= TRIALS; trial++) {
    const next = solver.next();
    if (next.done) {
      console.log(`${fromFile} is out of solutions.`);
      process.exit(1);
    }

    const trialFacts = [...next.value.lookup('at')]
      .map(([x, y, z]) => `at ${x} ${y} is ${z}.`)
      .sort()
      .join('\n');
    const toProgram = toRules + '\n' + trialFacts + '\n' + songText;
    const solution = new Dusa(toProgram).solution;

    if (solution) {
      console.log(`Trial ${trial}: passed`);
    } else {
      console.log(`Trial ${trial}: failed\n`);
      console.log(toProgram);
      console.log('# The above Dusa program has no solutions!');
      process.exit(1);
    }
  }
}

checkRules(RULES_FILE_1, RULES_FILE_2);
checkRules(RULES_FILE_2, RULES_FILE_1);
